### ISSUE TITLE
Possible Error on Quiz

### ISSUE THREAD

**Issue by dknuckle** [learn-co-curriculum/phase-1-quiz-javascript-fundamentals#1]
### Canvas Link

https://my.learn.co/courses/650/quizzes/6978

### Concern

It seems I got a question partially correct but when it shows me the correct answer it is the exact same thing I had typed in. Possible bug with quiz?

### Additional Context

![possible_error_on_quiz](https://user-images.githubusercontent.com/122567677/225485673-c8554cae-130b-4b08-8083-16113d8f6707.png)

### Suggested Changes

Correct bug so others do not get dinged if they correctly answer the question

**Comment by dknuckle** [comment]
Hmm I think I may have figured out _**my**_ issue. Sorry for this

**Comment by lizbur10** [comment]
Hi @dknuckle! I'm glad to hear that because I was very confused! 😆 

Thanks for contributing to the Flatiron School curriculum 💙
